default:
  autoload:
    '': '%paths.base%/../features/bootstrap'
  suites:
    webUI:
      paths: ['%paths.base%/../features/webUI']
      contexts:
        - FeatureContext:
        - WebContext:
  extensions:
    SensioLabs\Behat\PageObjectExtension: ~
    rdx\behatvars\BehatVariablesExtension: ~
    Cjm\Behat\StepThroughExtension: ~
    Behat\MinkExtension:
      browser_name: 'chrome'
      base_url: 'http://localhost/core'
      selenium2:
        wd_host: 'http://localhost:4444/wd/hub'
        capabilities:
          browser: 'chrome'
          browserName: 'chrome'
          marionette: null
          platform: 'linux'
          name: 'test-mink'
          extra_capabilities:
            maxDuration: '3600'
            goog:chromeOptions:
              # args: ['--headless', '--disable-gpu']
